<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>යතුරු කරනය ඉගන ගනිමු</title>

        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
            #game {
                display: none;
            }
            #welcome {
                display: block;
            }
            #help {
                display: none;
            }

            footer {
                position: relative;
                height: 30px;
                bottom: 0;
                width: 100%;
            }
        </style>
    </head>
    <body oncopy="return false" oncut="return false" onpaste="return false">
        <div class="container-fluid" id="welcome">
            <div class="row">
                <div class="col-xs-12 text-right" style="padding-left: 0px; padding-right: 0px; background-image: url(img/bghead.png); background-position: left; background-repeat: no-repeat; ">
                    <h1 class="vtop">ආයුබෝවන්</h1>
                </div>
                <div class="col-xs-12 text-right">
                    <h1 style="margin-top: 0px; margin-bottom: 0px;"><small>විනෝදමත් අද්‍යාපනය</small></h1>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 text-center small vcenter">සිංහල යතුරු පුවරැවක් අව්‍ශ්‍ය උපදෙස් බොත්තම කොටන්න</div>
                <div class="visible-xs">&nbsp;</div>
                <div class="col-xs-12 col-sm-6 col-md-6 text-center">
                    <button id="showHelp" class="btn btn-default btn-info">යතුරු ලියන උපදෙස්</button>
                </div>
            </div>
            <hr />
            <div class="row" style="height: 130px;">
                <div class="col-xs-12">
                    <h4 class="text-left" style="color: green;"><strong>තරග වදින හැටි</strong></h4>
                </div>
                <div class="col-xs-12">
                    <ul style="line-height: 30px;">
                        <li>ආරම්භය කොටන්න</li>
                        <li>දකින වචනය ටයිප් කරන්න</li>
                        <li>ශුද්ධ සිංහල පමණි (ෆොනෙටික් භාවිතා නොකරන්න)</li>
                    </ul>
                </div>
            </div>
            <hr />
            <div class="row" style="height: 100px; vertical-align: middle;">
                <div class="col-xs-12 col-md-12 text-center" style="padding-top: 10px;">
                    <label class="radio-inline"><input type="radio" name="difficulty" id="easy" value="easy" checked>ලේසි</label>
                    <label class="radio-inline"><input type="radio" name="difficulty" id="medium" value="medium">ෂෙප්</label>
                    <label class="radio-inline"><input type="radio" name="difficulty" id="hard" value="hard">අපෝ</label>
                    <label class="radio-inline"><input type="radio" name="difficulty" id="expert" value="expert">උගුල</label>
                </div>
                <div class="col-xs-12 text-center" style="padding-top: 10px;">
                    <button class="btn btn-primary btn-lg startButton">ආරම්භය</button>
                </div>
            </div>
            <hr />
        </div>
        <div class="container-fluid" id="game">
            <div class="row" style="border-radius: 4px; height: 30px; margin-top: 15px; background-color: #1b6d85; margin-left: 20px; margin-right: 20px; color: white; font-size: 18px; font-weight: bold;">
                <div class="col-xs-6 text-left"><span>කාලය:&nbsp;&nbsp;</span><span id="timer">60.000</span></div>
                <div class="col-xs-6 text-right"><span>ලකුණු:&nbsp;&nbsp;</span><span id="score">0</span></div>
            </div>

            <div class="row" style="margin-top: 5px;">
                <div class="col-xs-12 text-center"><h1 id="currentWord">5</h1></div>
                <div class="col-xs-12">
                    <textarea id="type-here" style="font-size: 26px !important; font-weight: bold !important;" class="form-control" rows="1"></textarea>
                    <div id="resultHolder" style="display: none; text-align: center; font-size: 16px; color: white; height: 80px; padding: 10px 5px; line-height: 2;">
                        <span id="resultOfGame"></span> <br/>
                        ලකුණු:<span id="spanScore" style="color: black;">732</span>
                        කාලය: <span id="spanTime" style="color: black;">53.74</span>
                        ක්ෂමතාව: <span id="spanEfficency" style="color: black;">71.54%</span>
                        විනාඩි/වචන: <span id="spanWPM" style="color: black;">9</span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-1">&nbsp;</div>
                <div class="col-xs-10">
                    <div id='infoPanel' class="alert alert-danger text-center bold" role="alert" style="font-weight: bold; padding: 2px; margin-bottom: 5px;"></div>
                    <div id='replayPanel' class="alert alert-info text-center bold" role="alert" style="font-weight: bold; display: none;">
                        <button class="btn btn-primary btn-lg startButton">නැවත කරමු</button>
                    </div>
                </div>
                <div class="col-xs-1">&nbsp;</div>
            </div>

            <pre id="debug" style="display: none;"></pre>
            <h4 style="border-bottom: gray 1px solid;">ලකුනු පුවරැව</h4>
            <div class="table-responsive">
                <table class="table table-stripe table-bordered" id="historyTable">
                    <thead>
                        <tr>
                            <th>ප්‍රයත්නය</th>
                            <th>කාලය (තත්පර)</th>
                            <th>ලකුණු</th>
                            <th>හරි/වැරදි</th>
                        </tr>
                    </thead>
                    <tbody id="history"></tbody>
                </table>
            </div>

        </div>


        <div class="container-fluid" id="help">
            <div class="row">
                <div class="col-xs-12 text-right">
                    <h1>ආයුබෝවන් <small>විනෝදමත් අද්‍යාපනය</small></h1>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-xs-12">
                    <h4>ස්තාපන උපදෙස්</h4>
                </div>
                <div class="col-xs-12">
                    <ul>
                        <li>වින්ඩෝස් - <a href="https://youtu.be/-Pplub4SJ3U">යුනිකෝඩ් වින්ඩෝස්</a></li>
                        <li>ඇනුඩ්‍රායිඩ් - <a href="https://play.google.com/store/apps/details?id=com.touchtype.swiftkey">ස්විෆ්ට් කී</a></li>
                        <li>අයිෆෝන් - <a href="http://keyman.com/sinhala/garp/">කී මැන්</a></li>
                        <li>ලිනක්ස් - <a href="http://sinhala.sourceforge.net/">සෝස් ෆාඡ්</a></li>
                        <li>ක්‍රෝම් - <a href="https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab">ශුද්ධ සිංහල පමණි</a></li>
                    </ul>
                </div>

                <div class="text-center col-xs-12" style="color: orangered;">කොපි පේස්ට් කිරිම සහ අනිත් ෆොනෙටික් වරයේ මෙවලමු උපයෝගී කරගැනීමේදි ලකුණු කැපියා හැක</div>

            </div>
            <hr />
            <div class="row" style="height: 100px; vertical-align: middle;">
                <div class="col-xs-6 text-center" style="padding-top: 30px;">
                    <button class="btn btn-primary btn-lg startButton">ආරම්භය</button>
                </div>
                <div class="col-xs-6 text-center" style="padding-top: 30px;">
                    <button class="btn btn-primary btn-lg welcomeButton">මුල් පිටුව</button>
                </div>
            </div>
            <hr />
        </div>



        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>

        <script type="text/javascript">

            //http://jrgraphix.net/r/Unicode/0D80-0DFF
            (function($){
                $.fn.shuffle = function() {
                    return this.each(function(){
                        var items = $(this).children();
                        return (items.length)
                            ? $(this).html($.shuffle(items))
                            : this;
                    });
                };

                $.shuffle = function(arr) {
                    for(
                        var j, x, i = arr.length; i;
                        j = parseInt(Math.random() * i),
                            x = arr[--i], arr[i] = arr[j], arr[j] = x
                    );
                    return arr;
                }
            })(jQuery);

            var timerValue = 60.00;
            var timeout = 5;
            var timeoutVal = null;
            var score = 0;
            var currentWord = null;
            var currentWordCodes = [];
            var typedSoFar = [];
            var wordScoreIndex = [];
            var wordScoreBegin = 0;
            var wordStart = 0.0;
            var wordStop = 0.0;
            var changeWord = false;
            var keyPressCount = 0;
            var cumulativeKeyPress = 0;
            var eraseCount = 0;
            var cumulativeEraseCount = 0;
            var correctCount = 0;
            var cumulativeCorrectCount = 0;
            var incorrectCount = 0;
            var cumulativeIncorrectCount = 0;
            var difficulty;

            var wordList = {easy: [], medium: [], hard: [], expert: []};

            wordList.easy = ["අම්මා", "මගුල් කෑම", "රැකියාව", "අලුත් අවුරුද්ද", "මිතුරා", "ජනාවාස", "සවාරිය", "ජනාධිපතිතුමා", "පියතුමා", "සිරිත් විරිත්"];
            wordList.medium = ["සාමර්ථ්‍යය", "අතුරුබාධනය", "කෘෂිකර්මය", "භූගෝලවිද්‍යාව", "පාර්ලිමේන්තුව", "දේශපාලන විද්‍යාව", "මාර්ගදර්ශකයා", "ලංකාදීපය", "කථානායක", "සනීතිඥයා"];
            wordList.hard = ["පෞරාණික", "නෂ්ටාවශේෂ", "ගරාවැටුණු ගොඩනැඟිලි ආදිය", "විශ්වවිද්‍යාලයයේ විද්‍යාංශය", "ඡ්‍යෝතිෂ්ශාස්ත්‍රය", "තාරකාශාස්ත්‍රය", "ගුවන් විදුලිය ප්‍රචාරය", "එකිනෙකා නසාගන්නා", "ලිංගික", "ආකාශයාත්‍රාව"];
            wordList.expert = ["අපකීර්තියට පමුණවනවා", "සාක්ෂරතාව", "මුහුදු රාජාලියා", "විශ්වවිද්‍යාලය", "විශ්ව විද්‍යාලයයක මහාචාර්යවරයා", "මූලධර්මය", "කාබොහයිඩේ‍්‍රට් පරිවෘත්තිය", "මරණීය දණ්ඩනය", "අතන්ද්‍රතාව", "ශුක්‍රාණුව"];
            var currentGameWordOrder = [];

            $(document).ready(function (e) {
                $(".startButton").click(function (e) {
                    $("#welcome").hide();
                    $("#help").hide();
                    $("#game").show();
                    $("#history").html("");
                    difficulty = $('input[name=difficulty]:checked').val();
                    //console.log(difficulty);
                    hideReply();
                    score = 0;
                    timerValue = 60.00;
                    timeout = 5;
                    currentWord = null;
                    currentGameWordOrder = wordList[difficulty].slice();
                    currentGameWordOrder = $.shuffle(currentGameWordOrder);
                    //console.log(currentGameWordOrder);
                    currentWordCodes = [];
                    wordScoreIndex = [];
                    wordScoreBegin = 0;
                    $("#type-here").val("");
                    $("#score").text(score);
                    $("#timer").text(timerValue);
                    timeoutVal = setInterval(function () {
                        $("#currentWord").text(--timeout);
                        $("#type-here").keyup(checkInput);
                        $("#infoPanel").show();
                        $("#replayPanel").hide();
                        if (timeout == 0) {
                            $("#infoPanel").text("ඉහල වචනය ඉක්මනින් ටයිප් කරන්න");
                            clearInterval(timeoutVal);
                            timeoutVal = null;
                            if (timeoutVal === null) timeoutVal = setInterval(reduceTime, 10);
                            showNextWord();
                        }
                    }, 1000);
                });
                $("#showHelp").click(function (e) {
                    $("#welcome").hide();
                    $("#help").show();
                });
                $(".welcomeButton").click(function (e) {
                    $("#welcome").show();
                    $("#help").hide();
                });
                $('body, #currentWord').bind('copy paste cut',function(e) {
                    e.preventDefault(); return false;
                });
            });

            //U+0D80..U+0DFF
            function isSinhalaLetter(letter) {

                return /[^\u0d80-\u0dff]/.test(letter);
            }

            function fixedCharCodeAt(str, idx) {
                // ex. fixedCharCodeAt('\uD800\uDC00', 0); // 65536
                // ex. fixedCharCodeAt('\uD800\uDC00', 1); // false
                idx = idx || 0;
                var code = str.charCodeAt(idx);
                var hi, low;

                // High surrogate (could change last hex to 0xDB7F to treat high
                // private surrogates as single characters)
                if (0xD800 <= code && code <= 0xDBFF) {
                    hi = code;
                    low = str.charCodeAt(idx + 1);
                    if (isNaN(low)) {
                        throw 'High surrogate not followed by low surrogate in fixedCharCodeAt()';
                    }
                    return ((hi - 0xD800) * 0x400) + (low - 0xDC00) + 0x10000;
                }
                if (0xDC00 <= code && code <= 0xDFFF) { // Low surrogate
                    // We return false to allow loops to skip this iteration since should have
                    // already handled high surrogate above in the previous iteration
                    return false;
                    /*hi = str.charCodeAt(idx - 1);
                     low = code;
                     return ((hi - 0xD800) * 0x400) + (low - 0xDC00) + 0x10000;*/
                }
                return code;
            }

            function checkInput(e) {
                var keyPress = e.which;
                if (keyPress === 16) return true;
                //console.log(e);
                var currentText = $("#type-here").val().trim();
                var position = currentText.length - 1;
                var currentCode = fixedCharCodeAt(currentText, currentText.length - 1);
                var isCorrectChar = currentWordCodes[position] === currentCode;
                var isFirstTime = (wordScoreIndex[position] == 0);
                var isComplete = currentWord.length === currentText.length && currentWord === currentText;

                keyPressCount++;
                cumulativeKeyPress++;
                if (keyPress === 8) {
                    if (isCorrectChar && isFirstTime) {
                        score -= 10; //we are going to take remove the score to prevent score hacking
                    }
                    eraseCount++;
                    cumulativeEraseCount++;
                    return true;
                }


                if (isCorrectChar) {
                    correctCount++;
                    cumulativeCorrectCount++;
                    if (isFirstTime) {
                        score += 10;
                    } else {
                        score += 3;
                    }
                    if (isComplete) {
                        wordStop = timerValue;
                        if (putScore(true)) {
                            if (currentGameWordOrder.length === 0) {
                                clearInterval(timeoutVal);
                                $("#type-here").unbind('blur').unbind('keyup');
                                timeoutVal = null;
                                showReplay();
                                showWon();
                            } else {
                                $("#score").text(score);
                                return showNextWord();
                            }
                        } else {
                            return false;
                        }
                    }
                } else {
                    incorrectCount++;
                    cumulativeIncorrectCount++;
                    if (isFirstTime) {
                        score -= 5;
                        wordScoreIndex[position] = 1; //first mistake
                    } else {
                        score -= 4;
                    }
                }
                $("#score").text(score);
            }

            function showReplay() {
                $("#infoPanel").hide();
                $("#replayPanel").show();
            }

            function hideReply() {
                $("#replayPanel").hide();
                $("#resultHolder").hide();
                $("#infoPanel").show();
                $("#type-here").show();
            }

            function showWon() {
                $("#type-here").hide();
                $("#resultHolder").css("background-color", "#c7e597").show();
                $("#resultOfGame").text("ඔබ දිනුම්....");
                setScoreText();
            }
            
            function showLost() {
                $("#type-here").hide();
                $("#resultHolder").css("background-color", "#e85167").show();
                $("#resultOfGame").text("කාලය අවසන්");
                setScoreText(false);
            }

            function setScoreText(won) {
                var wpm = (wordList[difficulty].length - currentGameWordOrder.length);
                if (!won) wpm--;
                $("#spanScore").text(score);
                $("#spanTime").text((60.0 - timerValue).toFixed(2));
                $("#spanEfficency").text((cumulativeCorrectCount / cumulativeKeyPress * 100).toFixed(2));
                $("#spanWPM").text(wpm);
            }

            function putScore(running) {
                var timeTaken = wordStart - wordStop;
                var wordScore = score - wordScoreBegin;
                var fullScorePotential = (currentWord.length * 10);
                var efficiency = (correctCount / keyPressCount * 100).toFixed(2);

                var color = "danger";
                if (timeTaken < 5 && wordScore > (fullScorePotential * 0.80) && efficiency > 75.00 ) {
                    color = "success";
                } else if (timeTaken > 5 && timeTaken < 10 && wordScore > parseInt(fullScorePotential * 0.50) && efficiency >= 50.00) {
                    color = "warning";
                } else {
                    color = "danger";
                }
                var tr = document.createElement("tr");
                var tdWord = document.createElement("td");
                var tdTime = document.createElement("td");
                var tdScore = document.createElement("td");
                var tdEffi = document.createElement("td");
                tdWord.innerText = currentWord;

                if (!running) {
                    tdTime.innerText = wordStart.toFixed(2);
                    score -= wordScore;
                    $("#score").text(score);
                    tdEffi.innerText = "-";
                    tr.className = "danger";
                } else {
                    tdTime.innerText = timeTaken.toFixed(2);
                    tdScore.innerText = wordScore + " / " + fullScorePotential;
                    tdEffi.innerText = efficiency + "%";
                    tr.className = color;
                }
                tr.appendChild(tdWord);
                tr.appendChild(tdTime);
                tr.appendChild(tdScore);
                tr.appendChild(tdEffi);
                $("#history").append(tr);

                /*if (running && wordScore > currentWord.length * 10) {
                    $("#type-here").unbind('blur').unbind('keyup');
                    clearInterval(timeoutVal);
                    console.log('something went wrong');
                    return false;
                }*/

                keyPressCount = 0;
                eraseCount = 0;
                correctCount = 0;
                incorrectCount = 0;
                return true;
            }

            function showNextWord() {
                currentWordCodes = [];
                wordScoreIndex = [];
                $("#type-here").unbind('keyup').unbind('blur');
                currentWord = currentGameWordOrder.pop();
                for (var i=0; i < currentWord.length; i++) {
                    currentWordCodes[i] = fixedCharCodeAt(currentWord, i);
                    wordScoreIndex[i] = 0;
                }
                $("#currentWord").text(currentWord);
                wordStart = timerValue;
                wordScoreBegin = score;
                $("#type-here").val('').focus().keyup(checkInput).blur(function () {
                    score = score - 100;
                    $("#score").text(score);

                    $("#infoPanel").text("ලකුණු 100 කැපී ඇත (හොර)");
                    setTimeout(function() {
                        $("#infoPanel").text("ඉහල වචනය ඉක්මනින් ටයිප් කරන්න");
                    }, 5000);

                });
                return true;
            }

            function reduceTime() {
                timerValue = timerValue - 0.01;
                if (timerValue <= 0.0) {
                    putScore(false);
                    clearInterval(timeoutVal);
                    showReplay();
                    showLost();
                    timeoutVal = null;
                }
                $("#timer").text(timerValue.toFixed(2));
            }
        </script>
        <footer class="footer text-center">
            2017 ඕල් රයිට්ස් රිසව්ඩ් - පිටුව සහ අපි
        </footer>

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-46942077-5', 'auto');
            ga('send', 'pageview');

        </script>
    </body>
</html>
